// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBjXyGeQcIRvzN_fNJMi_3DNb6TYPMZoY',
    appId: '1:1074976967601:web:f7b1f03b4e33d3f05f4b90',
    messagingSenderId: '1074976967601',
    projectId: 'diabetes-tracking-system-bca',
    authDomain: 'diabetes-tracking-system-bca.firebaseapp.com',
    storageBucket: 'diabetes-tracking-system-bca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgPEZsKVMvBMdrMKGo87U8QAC17sW9rik',
    appId: '1:1074976967601:android:753636caf301850b5f4b90',
    messagingSenderId: '1074976967601',
    projectId: 'diabetes-tracking-system-bca',
    storageBucket: 'diabetes-tracking-system-bca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOt8a9oR_qW0tbHfoght-_qg7_N2mSm90',
    appId: '1:1074976967601:ios:f9858c05a32940ac5f4b90',
    messagingSenderId: '1074976967601',
    projectId: 'diabetes-tracking-system-bca',
    storageBucket: 'diabetes-tracking-system-bca.firebasestorage.app',
    iosBundleId: 'com.bcafinal.diabetesTrackingSystem',
  );
}
